### ISSUE TITLE
Feature Request: Save current settings to a file

### ISSUE THREAD

**Issue by ImFlizz** [Skymirrh/CompatibilityManager#1]
If we could export the current settings, then import them, it would be very useful when reinstalling Windows.

You could also have .exe files that you don't already have installed, so if you are uninstalling and installing games because of limited disk space, the setting is already there.

**Comment by nbusseneau** [comment]
You can actually already do that by exporting your registry settings to a .reg file. I'm not sure it'd be necessary to integrate an import/export option in the app, however having some kind of easy way to generate a .reg file instead of having to do it manually is a good idea.

I'll see what I can do about it during the next weekend :)

**Comment by nbusseneau** [comment]
Added in [v1.1.0](https://github.com/Skymirrh/CompatibilityManager/releases/tag/v1.1.0)!
